theme: jekyll-theme-minimal
title: gohei-mochi
description: 虹裏ライフをそこそこいい感じにする WebExtension
show_downloads: true
chrome_zip_url: https://github.com/toshiaki-gohei/gohei-mochi/releases/download/v1.0.0/gohei-mochi-chrome-1.0.0.zip
firefox_xpi_url: https://github.com/toshiaki-gohei/gohei-mochi/releases/download/v1.0.0/gohei-mochi-firefox-1.0.0.xpi
history: https://github.com/toshiaki-gohei/gohei-mochi/releases
normalize_css: https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.0/normalize.min.css
