theme: jekyll-theme-minimal
title: gohei-mochi
description: 虹裏ライフをそこそこいい感じにする WebExtension
show_downloads: true
zip_url: https://github.com/toshiaki-gohei/gohei-mochi/raw/gh-pages/archives/gohei-mochi-0.0.3.zip
